/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useMotionValue, useSpring } from "motion/react";
import { useFrame } from "@react-three/fiber";
import { Float, Html } from "@react-three/drei";

function Astronaut(props) {
  const { nodes } = useGLTF("/models/silver_surfer.glb");
  const group = useRef();

  // floating animation
  const yPosition = useMotionValue(5);
  const ySpring = useSpring(yPosition, { damping: 30 });
  useEffect(() => {
    ySpring.set(-1);
  }, [ySpring]);

  useFrame(() => {
    if (group.current) {
      group.current.position.y = ySpring.get();
    }
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[2, -1, 0]} // ✅ move right & a bit down
      rotation={[0, -Math.PI / 6, 0]} // ✅ slight rotation for perspective
      scale={2} // ✅ make it much bigger
    >
      <group
        position={[0, -0.032, -0.093]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.017, 0.027, 0.006]}
      >
        <mesh geometry={nodes.Object_12.geometry}>
          <meshStandardMaterial metalness={1} roughness={0.2} color="silver" />
        </mesh>
        <mesh geometry={nodes.Object_13.geometry}>
          <meshStandardMaterial metalness={1} roughness={0.2} color="silver" />
        </mesh>
        <mesh geometry={nodes.Object_14.geometry}>
          <meshStandardMaterial metalness={1} roughness={0.2} color="silver" />
        </mesh>
        <mesh geometry={nodes.Object_15.geometry}>
          <meshStandardMaterial metalness={1} roughness={0.2} color="silver" />
        </mesh>
        <mesh geometry={nodes.Object_16.geometry}>
          <meshStandardMaterial metalness={1} roughness={0.2} color="silver" />
        </mesh>
        <mesh geometry={nodes.Object_17.geometry}>
          <meshStandardMaterial metalness={1} roughness={0.2} color="silver" />
        </mesh>
        <mesh geometry={nodes.Object_18.geometry}>
          <meshStandardMaterial metalness={1} roughness={0.2} color="silver" />
        </mesh>
      </group>

      <mesh geometry={nodes.Object_4.geometry} scale={0.01}>
        <meshStandardMaterial metalness={1} roughness={0.2} color="silver" />
      </mesh>
      <mesh geometry={nodes.Object_6.geometry} scale={0.01}>
        <meshStandardMaterial metalness={1} roughness={0.2} color="silver" />
      </mesh>
      <mesh geometry={nodes.Object_8.geometry} scale={0.01}>
        <meshStandardMaterial metalness={1} roughness={0.2} color="silver" />
      </mesh>
      <mesh geometry={nodes.Object_10.geometry} scale={0.01}>
        <meshStandardMaterial metalness={1} roughness={0.1} color="white" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/silver_surfer.glb");

export default Astronaut;